apiVersion: v1
kind: pod
Metadata:
  name: nginx
  namespace: roboshop
  labels:
    name: nginx
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containers: 80
