apiVersion: v1
kind: Pod
metadata:
  name: resource
  labels:
    purpose: requests-limits
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        requests:
          cpu: "100m"
          memory: "68Mi"
        limits:
          cpu: "120m"
          memory: "100Mi"
          
